export const topics = [
  "Abnormal Psychology",
  "Accounting",
  "Acoustics",
  "Advertising",
  "Aerospace Engineering",
  "Aesthetics",
  "African Languages",
  "African Studies",
  "Agnosticism",
  "Agriculture",
  "Agronomy",
  "Anatomy",
  "Ancient History",
  "Analytical Chemistry",
  "Anthropology",
  "Archaeology",
  "Architectural Styles",
  "Architecture",
  "Archival Science",
  "Art History",
  "Art History Artists",
  "Art History Movements",
  "Artificial Intelligence",
  "Asian Studies",
  "Astronomy",
  "Atheism",
  "Augmented Reality",
  "Ballet",
  "Biochemistry",
  "Biography",
  "Biomedical Engineering",
  "Bird Identification",
  "Board Games",
  "Botany",
  "Broadcasting",
  "Buddhism",
  "Card Games",
  "Chemical Elements",
  "Chemical Engineering",
  "Christianity",
  "Civil Engineering",
  "Classical Greek Literature",
  "Classical Languages",
  "Classics",
  "Clinical Psychology",
  "Climatology",
  "Cognitive Psychology",
  "Coin Collecting",
  "Communication Studies",
  "Comparative Religion",
  "Computer Engineering",
  "Computer Networking",
  "Computer Science",
  "Constellations",
  "Constitutional Amendments",
  "Construction",
  "Conversational Phrases",
  "Creative Writing",
  "Criminology",
  "Culinary Arts",
  "Customs",
  "Cybersecurity",
  "Dance",
  "Data Science",
  "Data Structures & Algorithms",
  "Decision Theory",
  "Demography",
  "Dentistry",
  "Developmental Psychology",
  "Dietetics",
  "Digital Media",
  "Drama",
  "Drawing",
  "East Asian Languages",
  "Ecology",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Electromagnetism",
  "English Language",
  "English Literature",
  "Entomology",
  "Entrepreneurship",
  "Environmental Science",
  "Epistemology",
  "Ethics",
  "Ethnic Studies",
  "Ethology",
  "Etiquette",
  "Evolution",
  "Fiction",
  "Film Studies",
  "Finance",
  "Flags of the World",
  "Folklore",
  "Food Science",
  "Foreign Language Vocabulary",
  "Forensic Science",
  "Forestry",
  "French Literature",
  "Gardening",
  "Genealogy",
  "Gender Studies",
  "Genetics",
  "Geographical Capitals",
  "Geology",
  "German Literature",
  "German Language",
  "Germanic Languages",
  "Grammar",
  "Graphic Arts",
  "Greek Language",
  "Herpetology",
  "Hinduism",
  "Historical Dates",
  "Historical Events",
  "Horticulture",
  "Hospitality Management",
  "Human Resource Management",
  "Human-Computer Interaction",
  "Hydrology",
  "Ichthyology",
  "Idioms & Expressions",
  "Important Battles",
  "Improvisational Theater",
  "Inorganic Chemistry",
  "International Business",
  "International Relations",
  "Islam",
  "Italian Literature",
  "Journalism",
  "Judaism",
  "Key Signatures",
  "Kinesiology",
  "Latin Language",
  "Latin Literature",
  "Law",
  "Library Science",
  "Linguistics",
  "Literary Theory",
  "Logic",
  "Logical Fallacies",
  "Machine Learning",
  "Magic Shows",
  "Mammalogy",
  "Manufacturing",
  "Marketing",
  "Materials Science",
  "Mathematical Formulas",
  "Mathematics",
  "Mechanical Engineering",
  "Mechanics",
  "Medicine",
  "Metaphysics",
  "Meteorology",
  "Microbiology",
  "Middle Eastern Languages",
  "Military Science",
  "Mineral Identification",
  "Model Building",
  "Modern Dance",
  "Modern Greek Literature",
  "Museum Studies",
  "Music Theory",
  "Musical Instruments",
  "Musical Modes",
  "Musical Terms",
  "Musicals",
  "Musicology",
  "Mycology",
  "Mythology",
  "Neuropsychology",
  "Non-fiction",
  "Nuclear Physics",
  "Nursing",
  "Nutrition",
  "Occultism",
  "Oceanography",
  "Opera",
  "Operations Management",
  "Optics",
  "Organic Chemistry",
  "Ornithology",
  "Painting",
  "Paleontology",
  "Parapsychology",
  "Particle Physics",
  "Performing Arts",
  "Periodic Table",
  "Pharmaceutical Drug Names",
  "Pharmacy",
  "Phonetics & Pronunciation",
  "Philosophy of Language",
  "Philosophy of Mind",
  "Philosophy of Science",
  "Photography",
  "Physical Chemistry",
  "Physiology",
  "Poetry",
  "Political Philosophy",
  "Political Science",
  "Portuguese Literature",
  "Primatology",
  "Programming Concepts",
  "Programming Syntax",
  "Public Administration",
  "Public Health",
  "Public Relations",
  "Publishing",
  "Puzzles",
  "Quantum Mechanics",
  "Radio",
  "Real Estate",
  "Recreation and Leisure Studies",
  "Relativity",
  "Religious Studies",
  "Rhetoric",
  "Robotics",
  "Rock Identification",
  "Role-Playing Games",
  "Romance Languages",
  "Romanian Literature",
  "Sculpture",
  "Sign Languages",
  "Sikhism",
  "Slavic Languages",
  "Social Media",
  "Social Psychology",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Spanish Literature",
  "Sports Rules",
  "Sports Science",
  "Stamp Collecting",
  "Stand-up Comedy",
  "Standardized Test Prep",
  "Statistics",
  "Supreme Court Cases",
  "Systems Theory",
  "Television Shows",
  "Theater Studies",
  "Theology",
  "Theoretical Computer Science",
  "Thermodynamics",
  "Transportation Studies",
  "Tree Identification",
  "US Presidents",
  "Urban Studies",
  "Veterinary Medicine",
  "Video Games",
  "Virology",
  "Virtual Reality",
  "Web Development",
  "Writing Systems & Scripts"
];
